#!/usr/bin/env python3
"""Render the version-comparison tables into README.md between markers.

Answers one question at a glance: **where does a version the skills quote no
longer match the repository it was read from?**

Two tables:

  1. Claim comparison -- for every pin a skill records a verified value for, the
     recorded value against the live one, per repository. This is the table that
     matters; a warning row means a skill is asserting behaviour it checked at a
     version nobody is running any more.
  2. The pin matrix -- what the watched upstreams actually ship right now, for
     calibration. There is no single "current" version in this family, and the
     matrix is the fastest way to see that.

Both are read live from the canonical upstreams, never from a clone.

Deliberately does NOT touch scripts/version_baseline.json. The baseline is the
*acknowledgement* that a human has re-read an affected claim; regenerating it
here would silently swallow the very alert check_versions.py exists to raise.
The table describes reality, the baseline records what has been accepted, and
they are allowed to disagree -- that disagreement is the finding.

Usage:
    python scripts/render_version_table.py            # rewrite the README block
    python scripts/render_version_table.py --check    # exit 1 if it is out of date
"""

import argparse
import datetime
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML is required: pip install pyyaml\n")
    raise SystemExit(2)

import check_versions as cv                                        # noqa: E402

START = "<!-- versions:start -->"
END = "<!-- versions:end -->"

MATRIX_KEYS = [
    ("BYOND", lambda p: "%s.%s" % (p.get("BYOND_MAJOR", "?"), p.get("BYOND_MINOR", "?"))),
    ("rust-g", lambda p: p.get("RUST_G_VERSION", "—")),
    ("Bun", lambda p: p.get("BUN_VERSION", "—")),
    ("tgui-core", lambda p: p.get("tgui-core", "—")),
    ("react", lambda p: p.get("react", "—")),
]


def read(path):
    with io.open(path, encoding="utf-8") as fh:
        return fh.read()


def comparison_rows(config, observed):
    """One row per (pin a skill records a value for) x (repository in its scope)."""
    rows = []
    repos = {r["id"]: r for r in config["repos"]}
    for key, link in sorted((config.get("claim_links") or {}).items()):
        recorded = [str(v) for v in link.get("verified_at", [])]
        scope = link.get("scope_repo")
        for repo_id in repos:
            if scope and scope != repo_id:
                continue
            actual = observed.get(repo_id, {}).get(key)
            if actual is None:
                continue                       # this repo does not pin it at all
            match = any(cv.normalize(actual) == cv.normalize(v) for v in recorded)
            rows.append({
                "key": key,
                "skill": link["skill"],
                "recorded": " / ".join(recorded) or "—",
                "actual": actual,
                "repo": repos[repo_id]["owner_repo"],
                "ok": match,
            })
    return rows


def render(config, observed, errors):
    stamp = datetime.datetime.now().strftime("%Y-%m-%d")
    out = [START, ""]
    out.append("<!-- Generated by scripts/render_version_table.py. Do not edit by hand;"
               " the workflow overwrites it. -->")
    out.append("")

    rows = comparison_rows(config, observed)
    mismatched = [r for r in rows if not r["ok"]]

    out.append("**Версия в скилле против реальной / Skill's version vs reality** "
               "— обновлено %s / updated %s" % (stamp, stamp))
    out.append("")
    out.append("| | Пин / Pin | В скилле / Skill records | Реально / Actual | "
               "Репозиторий / Repository | Скилл / Skill |")
    out.append("|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda r: (r["ok"], r["key"], r["repo"])):
        mark = "✅" if r["ok"] else "⚠️"
        out.append("| %s | `%s` | %s | `%s` | [%s](https://github.com/%s) | `%s` |"
                   % (mark, r["key"], r["recorded"], r["actual"], r["repo"], r["repo"],
                      r["skill"]))
    out.append("")

    if mismatched:
        out.append("⚠️ — реальная версия вне того, на чём проверялся скилл: утверждение не "
                   "опровергнуто, но его доказательство просрочено и требует перечитывания.")
        out.append("")
        out.append("*⚠️ means the live version sits outside what the skill was verified "
                   "against: the claim is not disproved, its evidence has expired.*")
    else:
        out.append("Все проверенные версии совпадают с тем, на чём писались скиллы.")
        out.append("")
        out.append("*Every recorded version still matches what the upstreams ship.*")
    out.append("")

    out.append("**Что реально стоит в апстримах / What the upstreams actually pin**")
    out.append("")
    header = "| Репозиторий / Repository | " + " | ".join(k for k, _ in MATRIX_KEYS) + " |"
    out.append(header)
    out.append("|---" * (len(MATRIX_KEYS) + 1) + "|")
    for repo in config["repos"]:
        pins = observed.get(repo["id"], {})
        if not pins:
            continue
        cells = [fn(pins) for _, fn in MATRIX_KEYS]
        out.append("| [%s](https://github.com/%s) | %s |"
                   % (repo["owner_repo"], repo["owner_repo"],
                      " | ".join("`%s`" % c if c != "—" else "—" for c in cells)))
    out.append("")
    out.append("Единой «текущей» версии в этом семействе нет — никогда не переносите версию "
               "из гайда одного форка в другой, читайте `dependencies.sh` цели.")
    out.append("")
    out.append("*There is no single \"current\" version in this family. Never carry a version "
               "from one fork's guide into another; read the target's own `dependencies.sh`.*")

    if errors:
        out.append("")
        out.append("Не удалось прочитать / could not read: "
                   + ", ".join("`%s/%s`" % (r, p) for r, p, _ in errors))

    out.append("")
    out.append(END)
    return "\n".join(out)


def splice(readme_text, block):
    if START not in readme_text or END not in readme_text:
        raise SystemExit("README.md has no %s / %s markers" % (START, END))
    head = readme_text[:readme_text.index(START)]
    tail = readme_text[readme_text.index(END) + len(END):]
    return head + block + tail


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except (ValueError, OSError):
                pass

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if the README block is out of date")
    parser.add_argument("--readme", default=None)
    parser.add_argument("--config", default=None)
    args = parser.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    readme_path = args.readme or os.path.join(root, "README.md")
    config_path = args.config or os.path.join(here, "version_watch.yaml")

    config = yaml.safe_load(read(config_path))
    observed, errors, transport = cv.collect(config, offline_ok=True)
    if not any(observed.values()):
        sys.stderr.write("No upstream could be read; refusing to render an empty table.\n")
        return 2

    block = render(config, observed, errors)
    current = read(readme_path)
    updated = splice(current, block)

    if args.check:
        if updated != current:
            print("README version block is out of date.")
            return 1
        print("README version block is current.")
        return 0

    if updated == current:
        print("README version block already current.")
        return 0

    with io.open(readme_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print("README version block updated (transport: %s)." % transport)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
